# Generated by Django 5.0.6 on 2024-07-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_marca"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={"verbose_name": "Categoria", "verbose_name_plural": "Categorias"},
        ),
        migrations.AlterModelOptions(
            name="cor",
            options={"verbose_name": "Cor", "verbose_name_plural": "Cores"},
        ),
        migrations.AlterModelOptions(
            name="marca",
            options={"verbose_name": "Marca", "verbose_name_plural": "Marcas"},
        ),
        migrations.RenameField(
            model_name="cor",
            old_name="descricao",
            new_name="nome",
        ),
    ]
