# Generated by Django 5.0.6 on 2024-07-15 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_categoria_options_alter_cor_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cor",
            old_name="nome",
            new_name="descricao",
        ),
    ]
